### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by gkiko** [freeuni-sdp/xo-rooms#22]
when requesting room list with signed-in user
`GET http://xo-rooms.herokuapp.com/?token=3bb64d2b-ebfd-4ebb-8a67-6e6e9bdb38cc 403 (Forbidden)`

**Comment by Meravici** [comment]
Is token passed valid?

**Comment by gkiko** [comment]
sandro sandro მომხმარებლით შევედი და ეგ დამიბრუნა სერვისმა

**Comment by Meravici** [comment]
Fixed
